
package org.pcchen.distribute.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ISayHelloServiceImplService", targetNamespace = "http://server.webservice.distribute.pcchen.org/", wsdlLocation = "http://localhost:8888/ceek/hello?wsdl")
public class ISayHelloServiceImplService
        extends Service {

    private final static URL ISAYHELLOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISAYHELLOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ISAYHELLOSERVICEIMPLSERVICE_QNAME = new QName("http://server.webservice.distribute.pcchen.org/", "ISayHelloServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ceek/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISAYHELLOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ISAYHELLOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ISayHelloServiceImplService() {
        super(__getWsdlLocation(), ISAYHELLOSERVICEIMPLSERVICE_QNAME);
    }

    public ISayHelloServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISAYHELLOSERVICEIMPLSERVICE_QNAME, features);
    }

    public ISayHelloServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ISAYHELLOSERVICEIMPLSERVICE_QNAME);
    }

    public ISayHelloServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISAYHELLOSERVICEIMPLSERVICE_QNAME, features);
    }

    public ISayHelloServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISayHelloServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns ISayHelloServiceImpl
     */
    @WebEndpoint(name = "ISayHelloServiceImplPort")
    public ISayHelloServiceImpl getISayHelloServiceImplPort() {
        return super.getPort(new QName("http://server.webservice.distribute.pcchen.org/", "ISayHelloServiceImplPort"), ISayHelloServiceImpl.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ISayHelloServiceImpl
     */
    @WebEndpoint(name = "ISayHelloServiceImplPort")
    public ISayHelloServiceImpl getISayHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.webservice.distribute.pcchen.org/", "ISayHelloServiceImplPort"), ISayHelloServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISAYHELLOSERVICEIMPLSERVICE_EXCEPTION != null) {
            throw ISAYHELLOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ISAYHELLOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
